sudo: required
language: java
service: mysql
before_install:
- sudo apt-get update -qq
- sudo apt-get install maven openjdk-8-jre -y
before_script:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('hellokoding') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart 
script:
  - mvn package
  - mvn jetty:run&
deploy:
  provider: heroku
  api_key:
    secure: ${{ secrets.HEROKU_API_KEY }}
  app: sinauloginmaven
  run: 
    - mvn jetty:run --port $PORT
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
